---
layout: page
title: 'REfER'
permalink: /refer/
author: Nash
lang: fr
---

= AsciiDoc Syntax Quick Reference
Dan Allen; Sarah White
v1.0.3, 2014-12-28
:description: This guide is a quick reference for the common formatting markup and document elements in the AsciiDoc syntax.
:keywords: AsciiDoc, Asciidoctor, syntax, reference, cheatsheet
:imagesdir: images
:experimental:
:table-caption!:
:example-caption!:
:figure-caption!:
:idprefix:
:idseparator: -
:linkattrs:
:docref: http://asciidoctor.org/docs
:user-ref: {docref}/user-manual
:fontawesome-ref: http://fortawesome.github.io/Font-Awesome
:icon-inline: {user-ref}/#inline-icons
:icon-attribute: {user-ref}/#size-rotate-and-flip
:video-ref: {user-ref}/#video
:checklist-ref: {user-ref}/#checklists
:list-marker: {user-ref}/#custom-markers
:list-number: {user-ref}/#numbering-styles
:imagesdir-ref: {user-ref}/#imagesdir
:image-attributes: {user-ref}/#put-images-in-their-place
:toc-ref: {user-ref}/#table-of-contents
:para-ref: {user-ref}/#paragraph
:literal-ref: {user-ref}/#literal-text-and-blocks
:admon-ref: {user-ref}/#admonition
:bold-ref: {user-ref}/#bold-and-italic
:quote-ref: {user-ref}/#quotation-marks-and-apostrophes
:sub-ref: {user-ref}/#subscript-and-superscript
:mono-ref: {user-ref}/#monospace
:css-ref: {user-ref}/#custom-styling-with-attributes
:pass-ref: {user-ref}/#passthrough-macros
:mailinglist: http://discuss.asciidoctor.org

AsciiDoc is a mature, lightweight markup language for authoring notes, articles, documentation, books, web pages, slide decks and man pages in plain text.
{description}

[NOTE]
====
Several examples focus on the output generated by the HTML backend.
AsciiDoc produces complementary output when generating DocBook.

Most features labeled "`Asciidoctor only`" can be made available to the native AsciiDoc processor by using https://github.com/asciidoctor/asciidoctor/blob/master/compat/asciidoc.conf[this AsciiDoc configuration file] from the Asciidoctor project.
====

== Paragraphs

.Normal
----
Paragraphs don't require any special markup in AsciiDoc.
A paragraph is just one or more lines of consecutive text.

To begin a new paragraph, separate it by at least one blank line.
----

[.result]
====
Paragraphs don't require any special markup in AsciiDoc.
A paragraph is just one or more lines of consecutive text.

To begin a new paragraph, separate it by at least one blank line.
====

.Line breaks
----
To preserve a line break, end the line in a space followed by a plus sign. +
This results in a visible line break (e.g., `<br>`) between the lines.
----

[.result]
====
To preserve a line break, end the line in a space followed by a plus sign. +
This results in a visible line break (e.g., `<br>`) between the lines.
====

.Literal
----
A normal paragraph.

 A sequence of lines that begin with at least one space is a literal paragraph.
 Literal paragraphs are treated as preformatted text.
 The text is shown in a fixed-width font
 and endlines are preserved.

Another normal paragraph.
----

[.result]
====
A normal paragraph.

 A sequence of lines that begin with at least one space is a literal paragraph.
 Literal paragraphs are treated as preformatted text.
 The text is shown in a fixed-width font
 and endlines are preserved.

Another normal paragraph.
====

.Admonition
----
NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...
----

[.result]
====
NOTE: An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.

Here are the other built-in admonition types:

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...
====

NOTE: You can also create <<admon-bl,admonition blocks>>.

.Lead paragraph
----
[.lead]
This text will be styled as a lead paragraph (i.e., larger font).
----

[.result]
====
[.lead]
This text will be styled as a lead paragraph (i.e., larger font).
====

NOTE: The default Asciidoctor stylesheet automatically styles the first paragraph of the preamble as a lead paragraph.

.More Paragraph, Admonition and Literal Block Examples
****
See these sections in the Asciidoctor User Manual for more information and examples.

* {para-ref}[Paragraphs]
* {literal-ref}[Literal Text and Blocks]
* {admon-ref}[Admonitions]
****

== Formatted Text

.Bold, Italic, and Monospace
----
_italic phrase_

__i__talic le__tt__ers

*bold phrase*

**b**old le**tt**ers

*_bold italic phrase_*

**__b__**old italic le**__tt__**ers

`monospace phrase` and le``tt``ers

`_monospace italic phrase_` and le``__tt__``ers

`*monospace bold phrase*` and le``**tt**``ers

`*_monospace bold italic phrase_*` and le``**__tt__**``ers

`+inline literal passthrough+` (monospace text without substitutions)
----

[.result]
====
_italic phrase_

__i__talic le__tt__ers

*bold phrase*

**b**old le**tt**ers

*_bold italic phrase_*

**__b__**old italic le**__tt__**ers

`monospace phrase` and le``tt``ers

`_monospace italic phrase_` and le``__tt__``ers

`*monospace bold phrase*` and le``**tt**``ers

`*_monospace bold italic phrase_*` and le``**__tt__**``ers

`+inline literal passthrough+` (monospace text without substitutions)
====

.Custom Styling
----
Do werewolves believe in [small]#small print#?

[big]##O##nce upon an infinite loop.
----

[.result]
====
Do werewolves believe in [small]#small print#?

[big]##O##nce upon an infinite loop.
====

.Superscript and Subscript
----
^super^script phrase

~sub~script phrase
----

[.result]
====
^super^script phrase

~sub~script phrase
====

.Curved Quotes
----
'`single smart quotes`'

"`double smart quotes`"
----

[.result]
====
'`single smart quotes`'

"`double smart quotes`"
====

.More Text Formatting Examples
****
See these sections in the Asciidoctor User Manual for more information and examples.

* {bold-ref}[Bold and Italic Formatting]
* {quote-ref}[Quotation Marks and Apostrophes]
* {sub-ref}[Subscript and Superscript]
* {mono-ref}[Monospace Formatting]
* {css-ref}[Custom Styling with Attributes]
* {pass-ref}[Passthrough Macros]
****

== Document Header

IMPORTANT: A header is optional.
When you do add a header to your document, the only required element is a title.

CAUTION: The heade
